#!/bin/sh
set -e

case "$1" in
    remove|upgrade|deconfigure)
        if systemctl list-units --type=service --full --all | grep -q "navidrome.service"; then
            systemctl stop navidrome.service >/dev/null 2>&1 || true
            systemctl disable navidrome.service >/dev/null 2>&1 || true
        fi
        ;;
esac

exit 0
